代码库/社区/PC端/MVC框架/Com.Cos.Web/Areas/Exchange/Models/ConfirmOrderViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace Com.Cos.Web.Areas.Exchange.Models
{
    public class ConfirmOrderViewModel
    {
        /// <summary>
        /// 兑换id
        /// </summary>
        [Display(Name = "id")]
        public int Id { get; set; }
        /// <summary>
        /// 收货地址
        /// </summary>
        [Display(Name = "收货地址")]
        public string Address { get; set; }
        /// <summary>
        /// 兑换方式，会员兑换为0，身家兑换为1
        /// </summary>
        [Display(Name = "兑换方式")]
        public string Method { get; set; }
        /// <summary>
        /// 付款金额
        /// </summary>
        public string Money { get; set; }
        /// <summary>
        /// 押金
        /// </summary>
        public string Deposit { get; set; }
        /// <summary>
        /// 订单类型,0为兑换，1为租借
        /// </summary>
        public int Type { get; set; }

    }
}

代码库/社区/PC端/MVC框架/Com.Cos.Web/Areas/Exchange/Controllers/ExchangeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Com.Cos.BLL;
using Com.Cos.Common;
using Com.Cos.IBLL;
using Com.Cos.Web.Areas.Cooperation.Models;
using Com.Cos.Web.Areas.Exchange.Models;

namespace Com.Cos.Web.Areas.Exchange.Controllers
{
    /// <summary>
    /// 兑换/分享
    /// </summary>
    public class ExchangeController : Controller
    {
        private readonly Com.Cos.IBLL.IExchangeService _exchangeService;
        private readonly Com.Cos.IBLL.IMemberService _memberService;
        private readonly Com.Cos.IBLL.IExchangeClassService _exchangeClassService;
        private readonly Com.Cos.IBLL.IExchangeExamineService _exchangeExamineService;
        private readonly Com.Cos.IBLL.IImgService _imgService;
        private readonly Com.Cos.IBLL.IMailingAddressService _mailingAddressService;

        private readonly int _userId;//登录的用户id
        private readonly Com.Cos.Models.Member _member;  //登录的用户

        public ExchangeController()
        {
            _exchangeService = new ExchangeService();
            _memberService = new MemberService();
            _exchangeClassService = new ExchangeClassService();
            _exchangeExamineService = new ExchangeExamineService();
            _imgService = new ImgService();
            _mailingAddressService = new MailingAddressService();

            _userId = Com.Cos.Common.Public.GetLoginUid();  //登录的用户id
            _member = _memberService.Find(_userId);  //登录的用户

            ViewBag.Classes = _exchangeClassService.FindList();  //全部兑换分类
            ViewBag.Examines = _exchangeExamineService.FindList();  //全部兑换状态

        }

        /// <summary>
        /// 列表页
        /// </summary>
        /// <param name="examineUsName">兑换状态英文名</param>
        /// <param name="classUsName">分类英文</param>
        /// <param name="p">当前页</param>
        /// <returns></returns>
        // GET: Exc/ExcList/ee/class?p=1
        [AllowAnonymous, AcceptVerbs(HttpVerbs.Get)]
        [ActionName("ExcList")]
        public ActionResult Index(string examineUsName, string classUsName, string p)
        {
            int page = p.ToInt32();  //当前页
            string examineId = _exchangeExamineService.Find(examineUsName)?.ExamineId;  //兑换状态id
            string classId = _exchangeClassService.Find(classUsName)?.ClassId.ToString();  //兑换状态id

            page = page < 1 ? 1 : page;
            var exchanges = GetExchange(page, examineId, classId);
            ViewBag.Exchanges = exchanges;
            ViewBag.ExamineUsName = examineUsName;
            ViewBag.ClassUsName = classUsName;
            return View("Index");
        }
        /// <summary>
        /// 详情页
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        // GET: Exc/Detail/1
        [Authorize, AcceptVerbs(HttpVerbs.Get)]
        public ActionResult Detail(int id)
        {
            var exchange = _exchangeService.Find(id);
            exchange.Certificate = TWEBURL.WEB_URL_IMG + _imgService.Find(exchange.Certificate.ToInt32())?.ImgBigUrl;
            string[] imgs = exchange.ImgList.Split(',');
            exchange.ImgList = "";
            foreach (string img in imgs)
            {
                exchange.ImgList += TWEBURL.WEB_URL_IMG + _imgService.Find(img.ToInt32())?.ImgBigUrl + ",";
            }
            exchange.ImgList = exchange.ImgList.TrimEnd(',');
            exchange.Examine = exchange.Examine == null ? "0" : exchange.Examine == "0" ? "0" : exchange.Examine;
            exchange.ClassId = _exchangeClassService.Find(exchange.ClassId.ToInt32()).ClassName;

            ViewBag.Exchange = exchange;
            var member = _memberService.Find(exchange.UserId.ToInt32());  //发布该兑换信息的用户
            member.Portrait = TWEBURL.WEB_URL_IMG + member.Portrait;
            ViewBag.Member = member;
            return View("Detail");
        }
        /// <summary>
        /// 发布页
        /// </summary>
        /// <returns></returns>
        // GET: Exc/Publish
        [Authorize, AcceptVerbs(HttpVerbs.Get)]
        [ActionName("Publish")]
        public ActionResult Create()
        {
            return View("Create");
        }
        /// <summary>
        /// 发布事件
        /// </summary>
        /// <param name="exchangeViewModel"></param>
        /// <returns></returns>
        // POST: Exc/Publish
        [ValidateAntiForgeryToken, Authorize]
        [HttpPost, ActionName("Publish")]
        public ActionResult Create(ExchangeViewModel exchangeViewModel)
        {
            //var errors = ModelState.Values.SelectMany(v => v.Errors);
            if (ModelState.IsValid)
            {
                int userId = Com.Cos.Common.Public.GetLoginUid();

                Com.Cos.Models.Exchange exchange = new Cos.Models.Exchange
                {
                    UserId = userId.ToString(),
                    Title = exchangeViewModel.Title,
                    ItemName = exchangeViewModel.ItemName,
                    ItemCharacter = exchangeViewModel.ItemCharacter,
                    Constitute = exchangeViewModel.Constitute,
                    Source = exchangeViewModel.Source,
                    Price = exchangeViewModel.Price,
                    ClassId = exchangeViewModel.ClassId,
                    Describe = exchangeViewModel.Describe,
                    //Valuation1 = exchangeViewModel.Valuation1,
                    //Valuation2 = exchangeViewModel.Valuation2,
                    //Valuation3 = exchangeViewModel.Valuation3,
                    //Certificate = exchangeViewModel.Certificate,
                    ImgList = exchangeViewModel.ImgList,
                    Cover = exchangeViewModel.Cover,
                    AddTime = DateTime.Now,
                    Status = 1

                };
                exchange = _exchangeService.Add(exchange);
                if (exchange.Id > 0)
                {
                    return Json(Public.MessageJson(1, "发布成功"));
                }
                return Json(Public.MessageJson(0, "修改失败"));
            }
            return PartialView("_PartialCreate", exchangeViewModel);
        }
        /// <summary>
        /// 确认订单
        /// </summary>
        /// <param name="id">兑换id</param>
        /// <param name="type">订单类型，0为兑换，1为租借</param>
        /// <returns></returns>
        // GET: Exc/ConfirmOrder/1
        [Authorize, AcceptVerbs(HttpVerbs.Get)]
        public ActionResult ConfirmOrder(int id, int type)
        {
            var exchange = _exchangeService.Find(id);
            ViewBag.Member = _member;
            ViewBag.Id = id.ToString();
            ViewBag.Type = type.ToString();
            ViewBag.Exchange = exchange;
            GetAddress();
            GetVip();
            return View("ConfirmOrder");
        }

        /// <summary>
        /// 兑换事件
        /// </summary>
        /// <param name="collection"></param>
        /// <returns></returns>
        // POST: Exc/Detail
        [Authorize, HttpPost]
        public ActionResult Detail(FormCollection collection)
        {

            int eid = collection.Get("Eid").ToInt32();  //该兑换id
            var exchange = _exchangeService.Find(eid);
            if (exchange.Examine != "3")
            {
                return Json(Com.Cos.Common.Public.MessageJson(0, "该兑换不在兑换状态!"));
            }

            return Json(Com.Cos.Common.Public.MessageJson(1, ""));
        }
        /// <summary>
        /// 确认订单
        /// </summary>
        /// <returns></returns>
        // POST: Exc/ConfirmOrder
        [ValidateAntiForgeryToken]
        [Authorize, AcceptVerbs(HttpVerbs.Post)]
        public ActionResult ConfirmOrder(ConfirmOrderViewModel model)
        {
            if (ModelState.IsValid)
            {
                string subjet = "";
                if (model.Type == 0)  //兑换
                {
                    subjet = "兑换订单";
                }
                if (model.Type == 1)  //租借
                {
                    subjet = "租借订单";
                }
                string submit = Com.Cos.Common.AlipayHelper.BuildRequest(_userId.ToString(), model.Money, subjet, model.Id.ToString(),model.Address,model.Deposit,model.Method);
                return Content(submit, "text/html");
            }
            return View("ConfirmOrder", model);
        }
        #region 私有方法

        /// <summary>
        /// 获得列表页数据
        /// </summary>
        /// <param name="page">当前页</param>
        /// <param name="examineId">兑换状态id</param>
        /// <param name="classId">兑换分类id</param>
        /// <returns></returns>
        private List<ExchangeViewModel> GetExchange(int page, string examineId, string classId)
        {
            int totalRecord;
            var excs = _exchangeService.FindPageList(page, 8, examineId, classId, out totalRecord);
            ViewBag.PageIndex = page;
            ViewBag.PageSize = 6;
            ViewBag.TotalRecord = totalRecord;
            List<ExchangeViewModel> exchangeList = new List<ExchangeViewModel>();
            foreach (var exc in excs)
            {
                Type type = exc.GetType();
                string coverId = type.GetProperty("Cover").GetValue(exc, null);
                if (string.IsNullOrEmpty(coverId))  //如果没有封面，则取第一张图片
                {
                    string imgList = type.GetProperty("ImgList").GetValue(exc, null);
                    string[] imgs = imgList.Split(',');
                    coverId = imgs[0];
                }
                string cover = _imgService.Find(coverId.ToInt32())?.ImgSmallUrl;

                exchangeList.Add(new ExchangeViewModel
                {
                    Id = type.GetProperty("Id").GetValue(exc, null),
                    Cover = TWEBURL.WEB_URL_IMG + cover,
                    Nickname = type.GetProperty("Nickname").GetValue(exc, null),
                    Portrait = TWEBURL.WEB_URL_IMG + type.GetProperty("Portrait").GetValue(exc, null),

代码库/社区/PC端/MVC框架/Com.Cos.Web/Controllers/ImgController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using Com.Cos.BLL;
using Com.Cos.Common;
using Com.Cos.IBLL;
using Com.Cos.Models;

namespace Com.Cos.Web.Controllers
{
    public class ImgController : Controller
    {
        private IImgService _imgService;

        public ImgController()
        {
            _imgService = new ImgService();
        }

        /// <summary>
        /// 保存图片
        /// </summary>
        /// <param name="collection"></param>
        /// <returns></returns>
        // POST: Img/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                string bigImgs = collection.Get("BigImg");  //大图base64，以逗号隔开
                string smallImgs = collection.Get("SmallImg");  //缩略图base64，以逗号隔开
                List<string> bigImgList = bigImgs.Split("data:", StringSplitOptions.RemoveEmptyEntries).ToList();  //大图base64列表，缺少头部data:
                List<string> smallImgList = smallImgs.Split("data:", StringSplitOptions.RemoveEmptyEntries).ToList();  //缩略图base64列表，缺少头部data:
                string imgIds = "";
                for (int i = 0; i < bigImgList.Count; i++)
                {
                    string img1 = "data:" + bigImgList[i].TrimEnd(',');
                    string img2 = "data:" + smallImgList[i].TrimEnd(',');
                    string md5 = Com.Cos.Common.DEncryptUtils.MD5Encrypt(img1);
                    //判断图片是否已经存在,如果已经保存则直接使用不再保存
                    Img oImg = _imgService.Find(md5);
                    if (oImg == null)
                    {
                        //获取文件名，文件名=时间戳+随机数
                        int timeStamp = Com.Cos.Common.DateTimeHelper.ConvertDateTimeInt(DateTime.Now);
                        Random ro = new Random();
                        string tt = timeStamp.ToString() + ro.Next();  // 文件名
                        oImg = new Img
                        {
                            ImgBigUrl = Com.Cos.Common.UploadFile.UploadImg(img1, "D:\\ftp\\web\\img.52cos.cn", "upload\\photo\\", tt),
                            ImgSmallUrl = Com.Cos.Common.UploadFile.UploadImg(img2, "D:\\ftp\\web\\img.52cos.cn", "upload\\photo\\", tt + "320x180"),
                            Md5 = md5,
                            AddTime = DateTime.Now,
                            Status = 1
                        };
                        oImg = _imgService.Add(oImg);
                    }

                    imgIds += oImg.Id + ",";
                    System.Threading.Thread.Sleep(1);
                }

                return Json(new Dictionary<string, string>() { { "status", "success" }, { "message", "图片保存成功" }, { "imgIds", imgIds.TrimEnd(',') } });
            }
            catch (Exception ex)
            {
                Com.Cos.Common.WriteLogHelper.WriteError(ex);
                return Json(new Dictionary<string, string>() { { "status", "error" }, { "message", ex.Message } });
            }
        }

    }
}

代码库/社区/PC端/MVC框架/Com.Cos.Web/Controllers/MemberController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Com.Cos.BLL;
using Com.Cos.Common;
using Com.Cos.IBLL;
using Com.Cos.Web.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;

namespace Com.Cos.Web.Controllers
{
    /// <summary>
    /// 会员
    /// </summary>
    public class MemberController : Controller
    {

        private IMemberService _memberService;

        public MemberController()
        {
            _memberService = new MemberService();
        }

        /// <summary>
        /// 判断邮箱或手机是否已经存在
        /// </summary>
        /// <param name="email"></param>
        /// <returns></returns>
        [AllowAnonymous,AcceptVerbs(HttpVerbs.Get)]
        public ActionResult CheckEmail(string email)
        {
            bool b;
            if (RegexUtil.IsEmail(email))  //是email
            {
                b = _memberService.Exist("Email", email);
            }
            else
            {
                
                b = _memberService.Exist("Phone_mob", email);
            }
            if (b)
            {
                ModelState.AddModelError("Email", "已存在的邮箱或手机号");
                return Json(false, JsonRequestBehavior.AllowGet);
            }
            return Json(true, JsonRequestBehavior.AllowGet);
        }
        /// <summary>
        /// 判断邮箱是否存在
        /// </summary>
        /// <param name="email">邮箱</param>
        /// <returns></returns>
        [Authorize, AcceptVerbs(HttpVerbs.Get)]
        public ActionResult CheckEmail2(string email)
        {
            int uid = Com.Cos.Common.Public.GetLoginUid();
            var user = _memberService.Find(m=>m.Email==email);

            return Json(user==null || user.User_id == uid, JsonRequestBehavior.AllowGet);
        }
        /// <summary>
        /// 确认手机号是否是绑定的手机号
        /// </summary>
        /// <param name="phoneMobile"></param>
        /// <returns></returns>
        [Authorize,AcceptVerbs(HttpVerbs.Get)]
        public ActionResult CheckPhone(string phoneMobile)
        {
            int uid = Com.Cos.Common.Public.GetLoginUid();
            var user = _memberService.Find(uid);
            return Json(user.Phone_mob == phoneMobile, JsonRequestBehavior.AllowGet);
            
        }
        /// <summary>
        /// 判断手机号是否存在
        /// </summary>
        /// <param name="phoneMob">手机号</param>
        /// <returns></returns>
        [Authorize, AcceptVerbs(HttpVerbs.Get)]
        public ActionResult ChekPhone2(string phoneMob)
        {
            int uid = Com.Cos.Common.Public.GetLoginUid();
            var user = _memberService.Find(m => m.Phone_mob == phoneMob);

            return Json(user == null || user.User_id == uid, JsonRequestBehavior.AllowGet);
        }
    }
}

代码库/社区/PC端/MVC框架/Com.Cos.Web/Areas/Exchange/Views/Exchange/ConfirmOrder.cshtml
@using Com.Cos.Models
@model Com.Cos.Web.Areas.Exchange.Models.ConfirmOrderViewModel

@{
    ViewBag.Title = "确认订单";

    Member member = ViewBag.Member;
    bool isVip = ViewBag.Vip;
    string type = ViewBag.Type;
}

@section Css
{
    <link rel="stylesheet" href="~/Content/css/libs/address.css">
}
<div class="big">
    <div class="content clearfix">
        @using (@Html.BeginForm("ConfirmOrder", "Exchange", FormMethod.Post, new { @Target = "_blank",@Id="pay" }))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true)
            if (type == "0")
            {
                @Html.Partial("_PartialExchange", Model)
            }
            else
            {
                @Html.Partial("_PartiaRented", Model)
            }

        }

        <!--右侧 Start-->
        @Html.Partial("_PartialRight", member)
        <!--右侧 End-->
    </div>
</div>
<div class="adreHui">
    <img src="~/Content/img/imghtan.jpg" />
    <p>抱歉！您还不是我们的会员</p>
    <a href="@Url.Action("BuyVip","Member",new{area="Member"})">立即加入会员</a>
</div>
@Html.Partial("_PartiaAddress", member)

@section Scripts
{
    <script>
        //模拟单选
        //$('.selectADS').click(function () { $('.adreHui').show() });
        $('.addAddress span').click(function () { $('.dizhiss').show(); });
        $('.dizhiss button').click(function () { $('.dizhiss').hide(); });
        //上面都是刚刚添加的


        $('div.border_radiu').click(function () {
            if (!$(this).hasClass('select')) {
                $(this).siblings('font').show();
                $(this).parents('.address_1').siblings('').children('div.border_radiu').siblings('font').hide();
                $(this).parents('.address_1').siblings('').children('div.border_radiu').siblings('span').removeClass('selectADS');
                $(this).siblings('span').addClass('selectADS');
            }
            $(this).parents('.address_1').siblings('').children('div.border_radiu').removeClass('select');
            $(this).addClass('select');
            $(this).find('img').attr('src', '/Content/img/blue_dian.jpg');
            $(this).parents('.address_1').siblings('').children('div.border_radiu').find('img').attr('src', '/Content/img/gray_dian.jpg');
        });
    </script>

    <script>
        $(document).ready(function () {
            //收货地址点击
            $(".address .dressBox .border_radiu").click(function () {
                var address = $(this).next("span").attr("data-value");
                var addText = $(this).next("span").text().replace("收) ", "收)<br />");
                $("#Address").val(address);
                $(".payInfo .adss span").html(addText);
            });
            
            //点击选择兑换方式
            $(".leftMiddle .radio .address_1").click(function () {
                var vip = $("span", this).attr("data-value");
                var vipText = $("span", this).text();
                $("#Method").val(vip);
                $(".payInfo .adss").next(".shifu").find("span").text(vipText);
                if (vipText == "单次租赁") {
                    $(".payInfo.clearfix .fk").find("span").text(145);
                    $('#Money').val(145);
                } else {
                    $(".payInfo.clearfix .fk").find("span").text(115);
                    $('#Money').val(115);
                }

            });

            $(".address .dressBox .border_radiu:eq(0)").trigger("click");

            $(".payBtn").click(function () {
                $("#pay").submit();
            });
        });
    </script>
    
    @if (type == "0")
    {
        <script>
            $(".leftMiddle .radio .address_1 .border_radiu:eq(0)").trigger("click");
        </script>
    }
    else
    {
        <script>
            //点击会员兑换时
            $(".leftMiddle .radio .address_1:eq(0)").click(function () {
                if ("@isVip" == "False") {
                    $('.adreHui').show();
                }

            });

            if ("@isVip" == "False") $(".leftMiddle .radio .address_1 .border_radiu:eq(1)").trigger("click");
            else $(".leftMiddle .radio .address_1 .border_radiu:eq(0)").trigger("click");
        </script>
    }
}

代码库/社区/PC端/MVC框架/Com.Cos.Web/Areas/Exchange/Views/Exchange/Create.cshtml
@model Com.Cos.Web.Areas.Exchange.Models.ExchangeViewModel

@{
    ViewBag.Title = "发布兑换";
}

@section Css
{
    <link rel="stylesheet" href="~/Content/css/libs/ReleaseCps.css">
}
<div class="big">
    <div class="content clearfix">
        <!--左侧菜单 Start-->
        @Html.Partial("_PartialLeftMenu")
        <!--左侧菜单 End-->
        @using (Html.BeginForm("Publish", "Exchange", FormMethod.Post))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true)
            <div class="middleContent" id="tb">
                @Html.Partial("_PartialCreate", Model)
            </div>
        }
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Scripts/libs/exif.js" type="text/javascript" language="javascript"></script>
    <script src="~/Scripts/libs/canvasJs.js" type="text/javascript" language="javascript"></script>
    <script src="~/Scripts/libs/picture.js" type="text/javascript" language="javascript"></script>
    <script>
        $(document).ready(function () {
            //单选，上传一张，缩略图显示容器，图片缓存容器，缩略图缓存容器
            //$('#aCertificate').fileUpload({ multiple: "", maxnum: 1, mapsel: 'map1', imgBox: '#hidCerBigImgs', imgBox2: "#hidCerSmallImgs", fileInput:"file-input1" }); //初始化图片上传
            //多选，上传一张，缩略图显示容器，图片缓存容器，缩略图缓存容器
            $('#aImgs').fileUpload({ multiple: "multiple", maxnum: 7, mapsel: 'map2', imgBox: '#hidItemBigImgs', imgBox2: "#hidItemSmallImgs", fileInput: "file-input2",index:0 }); //初始化图片上传

            //发布事件
            $("form[action$='Publish']").submit(function () {
                $("button[type='submit']", this).text("正在发布...").attr("disabled", "disabled").css("cursor", "not-allowed");

                //保存图片
                saveItemImg();

                return false;
            });

        });

        //保存凭证图
        @*function saveCertificate() {
            var bigImg = $("#hidCerBigImgs").val();
            var smallImg = $("#hidCerSmallImgs").val();
            $.post("@Url.Action("Create", "Img", new { area = "" })", { BigImg: bigImg, SmallImg: smallImg }, function (msg) {
                if (msg.status == "success") {
                    $("input[name='Certificate']").val(msg.imgIds);
                    saveItemImg();
                } else {
                    swal("OMG", msg.message, "error");
                    return false;
                }
            },"JSON").error(function() {
                swal("OMG", "系统繁忙，请稍后再试", "error");
                return false;
            });
        }*@
        //保存物品图
        function saveItemImg() {
            var bigImg = $("#hidItemBigImgs").val();
            var smallImg = $("#hidItemSmallImgs").val();
            $.post("@Url.Action("Create", "Img", new { area = "" })", { BigImg: bigImg, SmallImg: smallImg }, function (msg) {
                if (msg.status == "success") {
                    $("input[name='ImgList']").val(msg.imgIds);
                    Save();
                } else {
                    swal("OMG", msg.message, "error");
                    return false;
                }
            },"JSON").error(function() {
                swal("OMG", "系统繁忙，请稍后再试", "error");
                return false;
            });
        }

        function Save() {
            var thisObj = "form[action$='Publish']";
            //发布
            $.post($(thisObj).attr("action"), $(thisObj).serialize(), function (msg) {
                if (msg.status == "success") {
                    swalAlert.swalAlert("Good", msg.message, "3000", "success", false).then(function (result) {
                        $("button[type='submit']", this).text("发布").removeAttr("disabled").css("cursor", "pointer");
                        window.location.reload();
                    });
                } else if (msg.status == "error") {
                    swal("OMG", msg.message, "error");
                } else {
                    document.getElementById("tb").innerHTML = msg;
                }
            }).error(function () {
                swal("OMG", "系统繁忙，请稍后再试", "error");
                return false;
            });
        }
    </script>
}

代码库/社区/PC端/MVC框架/Com.Cos.Web/Areas/Exchange/Views/Exchange/Detail.cshtml
@using Com.Cos.Common
@using Com.Cos.Models



@{
    ViewBag.Title = "兑换详情页";
    Exchange exchange = ViewBag.Exchange;
    Member member = ViewBag.Member;

}

@section Css{
    <link rel="stylesheet" href="~/Content/css/libs/exchange.css">
}

<div class="big">
    <div class="content clearfix">
        <div class="leftContent">
            <div class="leftTop">
                <h3>@exchange.Title<span>发布时间：@exchange.AddTime.ToString("yyyy-MM-dd")</span></h3>
                <p>物品包括：<span>@exchange.Constitute</span></p>
                <p>物品来源：<span>@exchange.Source</span></p>
                <p>物品分类：<span>@exchange.ClassId</span></p>
                <p>其他描述：<span>@exchange.Describe</span></p>
                <p>原价：<span>@exchange.Price</span></p>
                @*<p>购买凭证：<span></span></p>
                    <div class="pingzheng">
                        <img src="@exchange.Certificate">
                    </div>*@
            </div>
            <div class="leftMiddle">
                <h3>物品详情图</h3>
                @{
                    string[] imgs = exchange.ImgList.Split(',');
                    foreach (string img in imgs)
                    {
                        <img src="@img" />
                    }
                }
            </div>
            <div class="leftBottom clearfix">
                <input type="hidden" name="eid" value="@exchange.Id" />
                <div class="pingfen clearfix">
                    <span>状态：</span>
                    <div class="progress" style="padding-right: 25px; margin: 25px 0 0 20px;">
                        <ul class="clearfix">
                            <li>审核中</li>
                            <li>回收中</li>
                            <li>可兑换</li>
                            <li>已兑换</li>
                            <li>已结束</li>
                        </ul>
                        <div class="gress">
                            <span class="blueGress" style="width: @(365 / 5 * (exchange.Examine.ToInt32()))px">
                                <i>
                                    <img src="~/Content/img/icon.png" />
                                </i>
                            </span>
                        </div>
                    </div>
                </div>
                @*<div class="pingfen clearfix">
                        <span>公投值：</span>
                        <div class="mark">
                            <img src="~/Content/img/xinxin.png">
                            <span>@exchange.Valuation1</span>
                        </div>
                        <div class="mark">
                            <img src="~/Content/img/xinxin.png">
                            <span>@exchange.Valuation2</span>
                        </div>
                        <div class="mark">
                            <img src="~/Content/img/xinxin.png">
                            <span>@exchange.Valuation3</span>
                        </div>
                    </div>*@
                <div class="pingfen clearfix">
                    <span>最终值：</span>
                    <div class="mark">
                        <img src="~/Content/img/xinxin.png">
                        <span>@exchange.Official</span>
                    </div>
                </div>
                <div class="butChange">
                    <button type="submit" data-value="0">兑换</button>
                    <button type="submit" data-value="1">租借</button>
                </div>
            </div>
        </div>
        <!--右侧 Start-->
        @Html.Partial("_PartialRight", member)
        <!--右侧 End-->

    </div>
</div>

@section Scripts
{
    <script>
        $(document).ready(function () {
            $("button[type='submit']").click(function () {
                var eid = $("input[name='eid']").val();
                var type = $(this).attr("data-value");
                $.post('@Url.Action("Detail", "Exchange", new {Area="Exchange",})', { Eid: eid }, function (msg) {
                    if (msg.status == "success") {
                        if (type == 0) {
                            window.location.href = '@Url.Action("ConfirmOrder", "Exchange", new {Area="Exchange", id = exchange.Id,type=0 })';
                        } else {
                            window.location.href = '@Url.Action("ConfirmOrder", "Exchange", new {Area="Exchange", id = exchange.Id,type=1 })';
                        }

                    } else {
                        swal('OMG', '该兑换不在兑换状态！', 'error');
                    }
                });

                return false;
            });
        });
    </script>

}