代码库/社区/PC端/Com.Cos/Com.Cos.Admin/Models/HomeViewModels/HomeViewModel.cs
namespace Com.Cos.Admin.Models.HomeViewModels
{
    public class HomeViewModel
    {
        /// <summary>
        /// 用户总数
        /// </summary>
        public int MemberCount { get; set; }
        /// <summary>
        /// 今天用户数
        /// </summary>
        public int TodayMemberCount { get; set; }
        /// <summary>
        /// 昨天用户数
        /// </summary>
        public int YesterdayMemberCount { get; set; }
        /// <summary>
        /// 会员总数
        /// </summary>
        public int VipCount { get; set; }
        /// <summary>
        /// 今天会员数
        /// </summary>
        public int TodayVipCount { get; set; }
        /// <summary>
        /// 昨天会员数
        /// </summary>
        public int YesterdayVipCount { get; set; }
        /// <summary>
        /// 访问量
        /// </summary>
        public int LoginCount { get; set; }
        /// <summary>
        /// 今天访问量
        /// </summary>
        public int TodayLoginCount { get; set; }
        /// <summary>
        /// 昨天访问量
        /// </summary>
        public int YesterdayLoginCount { get; set; }
    }
}

代码库/社区/PC端/Com.Cos/Com.Cos.Admin/Controllers/ExchangeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection.Metadata;
using System.Threading.Tasks;
using Com.Cos.Admin.Models;
using Com.Cos.Admin.Models.ExchangeViewModels;
using Com.Cos.Application.DTO;
using Com.Cos.Application.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Com.Cos.Admin.Controllers
{
    [Authorize]
    public class ExchangeController : Controller
    {
        private readonly IExchangeService _exchangeService;
        private readonly ILogisticService _logisticService;
        private readonly IExchangeClassService _exchangeClassService;
        private readonly IExchangeExamineService _exchangeExamineService;

        public ExchangeController(IExchangeService exchangeService, ILogisticService logisticService, IExchangeClassService exchangeClassService, IExchangeExamineService exchangeExamineService)
        {
            this._exchangeService = exchangeService;
            this._logisticService = logisticService;
            this._exchangeClassService = exchangeClassService;
            this._exchangeExamineService = exchangeExamineService;
        }

        // GET: Exchange
        [AllowAnonymous]
        public ActionResult Index()
        {
            var dtoList = _exchangeService.FindList();
            List<ExchageListViewModel> modelList = new List<ExchageListViewModel>();
            dtoList.ForEach(p =>
            {
                modelList.Add(ConvertHelper.ChangeType<ExchageListViewModel>(p));
            });

            ViewData["TotalCount"] = modelList.Count;
            ViewData["Exchages"] = modelList;
            return View();
        }

        //// GET: Exchange/Logistic
        //public IActionResult Logistic(string logisticCode)
        //{
        //    var dto = _logisticService.FindList(logisticCode);
        //    List<LogisticViewModel> modelList = new List<LogisticViewModel>();
        //    dto.ForEach(l => modelList.Add(ConvertHelper.ChangeType<LogisticViewModel>(l)));
        //    ViewBag.Logistic = logisticCode;
        //    ViewBag.LogisticList = modelList;
        //    return View();
        //}

        //// GET: Exchange/Details/5
        //public ActionResult Details(int id)
        //{

        //    //var dto = _exchangeService.Find(id, 0);
        //    //var model = new ExchangeDetailViewModel()
        //    //{
        //    //    AddTime = dto.AddTime.ToString("yyyy-MM-dd HH:mm:ss"),
        //    //    Constitute = dto.Constitute,
        //    //    Describe = dto.Describe,
        //    //    Id = dto.Id,
        //    //    Official = dto.Official,
        //    //    Price = dto.Price,
        //    //    Source = dto.Source,
        //    //    Title = dto.Title,
        //    //    Cover = dto.Cover,
        //    //    ImgList = dto.ImgDtoList.Select(img => "http://img.52cos.cn" + img.ImgPath).ToList()
        //    //};
        //    //ViewBag.ClassList = new SelectList(_exchangeClassService.FindList(), "Id", "ClassName", dto.ClassId);
        //    //ViewBag.ExamineList = new SelectList(_exchangeExamineService.FindList(), "Id", "ExamineName", dto.ExamineId);

        //    return View(model);
        //}

        //// GET: Exchange/Edit/5
        //public ActionResult Edit(int id)
        //{
        //    var dto = _exchangeService.Find(id, 0);
        //    var model = new ExchangeDetailViewModel()
        //    {
        //        AddTime = dto.AddTime.ToString("yyyy-MM-dd HH:mm:ss"),
        //        Constitute = dto.Constitute,
        //        Describe = dto.Describe,
        //        Id = dto.Id,
        //        Official = dto.Official,
        //        Price = dto.Price,
        //        Source = dto.Source,
        //        Title = dto.Title,
        //        Cover = dto.Cover,
        //        ImgList = dto.ImgDtoList.Select(img => "http://img.52cos.cn" + img.ImgPath).ToList()
        //    };
        //    ViewBag.ClassList = new SelectList(_exchangeClassService.FindList(), "Id", "ClassName", dto.ClassId);
        //    ViewBag.ExamineList = new SelectList(_exchangeExamineService.FindList(), "Id", "ExamineName", dto.ExamineId);

        //    return View(model);
        //}
        //// POST: Exchange/Edit/5
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Edit(int id, ExchangeDetailViewModel model)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        var dto = ConvertHelper.ChangeType<ExchangeDto>(model);

        //        MessageBase result = new MessageBase()
        //        {
        //            Status = _exchangeService.Update2(id, dto).ToString().ToLower()
        //        };

        //        return Json(result);
        //    }
        //    return View();
        //}






        ///// <summary>
        ///// 修改兑换状态
        ///// </summary>
        ///// <param name="id">兑换id</param>
        ///// <param name="examine">兑换状态</param>
        ///// <param name="official">最终值</param>
        ///// <returns></returns>
        //// POST: /Exchange/UpdateExamine
        //[HttpPost, ActionName("UpdateExamine")]
        //public ActionResult UpdateExamine(int id, string examine, string official)
        //{
        //    bool b = _exchangeService.UpdateExamine(id, examine, official);

        //    var msg = new MessageBase()
        //    {
        //        Status = b.ToString().ToLower()
        //    };
        //    return Json(msg);
        //}
        ///// <summary>
        ///// 删除
        ///// </summary>
        ///// <param name="id">兑换id</param>
        ///// <returns></returns>
        //// POST: Exchange/Delete/5
        //[HttpPost]
        //public ActionResult Delete(int id)
        //{
        //    MessageBase msg = new MessageBase();
        //    this._exchangeService.Delete2(id);
        //    msg.Status = "true";
        //    return Json(msg);
        //}
        ///// <summary>
        ///// 推荐
        ///// </summary>
        ///// <param name="id">兑换id</param>
        ///// <param name="status"></param>
        ///// <returns></returns>
        //// POST: /Exchange/Recommend
        //[HttpPost, ActionName("Recommend")]
        //public ActionResult Recommend(int id, int status)
        //{
        //    MessageBase result = new MessageBase();
        //    this._exchangeService.Recommend(id, status);

        //    return Json(result);
        //}

        //// GET: Exchange/Create
        //public ActionResult Create()
        //{
        //    return View();
        //}

        //// POST: Exchange/Create
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Create(IFormCollection collection)
        //{
        //    try
        //    {
        //        // TODO: Add insert logic here

        //        return RedirectToAction(nameof(Index));
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}

        // GET: Exchange/ExchangeDataJson
        [HttpGet,ActionName("ExchangeDataJson")]
        [AllowAnonymous]
        public async Task<ActionResult> ExchangeDataJson(int page, int limit)
        {
            var v = await _exchangeService.FindListAsync(page, limit);

            var r = new
            {
                Code = 0,
                Msg = "",
                Count = v.pageDto.TotalRecord,
                Data = v.dto
            };
            return new JsonResult(r);
        }

    }
}

代码库/社区/PC端/Com.Cos/Com.Cos.Admin/Controllers/ExchangePersonController.cs
using Com.Cos.Admin.Models.ExchangePersonViewModels;
using Com.Cos.Application.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using Com.Cos.Admin.Models;

namespace Com.Cos.Admin.Controllers
{
    [Authorize]
    public class ExchangePersonController : Controller
    {
        private readonly IExchangePersonService _exchangePersonService;
        public ExchangePersonController(IExchangePersonService exchangePersonService)
        {
            _exchangePersonService = exchangePersonService;
        }
        public IActionResult Index()
        {
            var dto = _exchangePersonService.FindList();
            List<ExchangePersonViewModel> modelList = new List<ExchangePersonViewModel>();
            dto.ForEach(e=>modelList.Add(ConvertHelper.ChangeType<ExchangePersonViewModel>(e)));
            ViewBag.EpList = modelList;

            return View();
        }


        /// <summary>
        /// 提交物流单号
        /// </summary>
        /// <param name="epId"></param>
        /// <param name="logistic">物流单号</param>
        /// <returns></returns>
        [HttpPost]
        public IActionResult UpdateLogistic(int epId,string logistic)
        {
            bool b =_exchangePersonService.UpdateLogistic(epId, logistic);

            var msg = new MessageBase()
            {
                Status = b.ToString().ToLower()
            };
            return Json(msg);
        }
    }
}

代码库/社区/PC端/Com.Cos/Com.Cos.Admin/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Com.Cos.Admin.Models;
using Com.Cos.Admin.Models.HomeViewModels;
using Com.Cos.Application.Interfaces;
using Microsoft.AspNetCore.Authorization;

namespace Com.Cos.Admin.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        private readonly IMemberService _memberService;
        private readonly ILoginIPService _loginIpService;
        public HomeController(IMemberService memberService,ILoginIPService loginIpService)
        {
            _memberService = memberService;
            _loginIpService = loginIpService;
        }
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        [Authorize(Roles = "0")]
        public IActionResult Welcome()
        {
            DateTime nowTime = DateTime.Now;
            HomeViewModel model = new HomeViewModel()
            {
                MemberCount = _memberService.GetUserCount(),
                TodayMemberCount = _memberService.GetUserCount(nowTime),
                YesterdayMemberCount = _memberService.GetUserCount(nowTime.AddDays(-1)),
                VipCount = _memberService.GetUserVipCount(),
                TodayVipCount = _memberService.GetUserVipCount(nowTime),
                YesterdayVipCount = _memberService.GetUserVipCount(nowTime.AddDays(-1)),
                LoginCount = _loginIpService.GetCount(),
                TodayLoginCount = _loginIpService.GetCount(nowTime),
                YesterdayLoginCount = _loginIpService.GetCount(nowTime.AddDays(-1))
            };
            return View(model);
        }
        [AllowAnonymous]
        public IActionResult Download()
        {
            return View();
        }
        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

代码库/社区/PC端/Com.Cos/Com.Cos.Admin/Controllers/MemberController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Com.Cos.Admin.Models.MemberViewModels;
using Com.Cos.Application.DTO;
using Com.Cos.Application.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace Com.Cos.Admin.Controllers
{
    public class MemberController : Controller
    {
        private readonly IBackMemberService _backMemberService;
        public MemberController(IBackMemberService backMemberService)
        {
            this._backMemberService = backMemberService;
        }
        public IActionResult Index()
        {
            var dtoList = _backMemberService.FindList();
            var modelList = new List<MemberListViewModel>();
            foreach (MemberDto dto in dtoList)
            {
                modelList.Add(new MemberListViewModel()
                {
                    Id = dto.Id,
                    Nickname = dto.Nickname,
                    Gender = dto.Gender,
                    PhoneMob = dto.PhoneMob,
                    IsVip = dto.IsVip,
                    AddTime = dto.AddTime.ToString("yyyy-MM-dd HH:mm:ss"),
                    Address = dto.Address
                });
            }
            ViewBag.MemberList = modelList;
            return View();
        }

        public IActionResult Refund()
        {

            return View();
        }
    }
}

代码库/社区/PC端/Com.Cos/Com.Cos.Admin/Controllers/RefundController.cs
using Com.Cos.Admin.Models;
using Com.Cos.Admin.Models.RefundViewModels;
using Com.Cos.Application.Interfaces;
using Com.Cos.Infrastructure.Ali;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Globalization;
using Com.Cos.Infrastructure;

namespace Com.Cos.Admin.Controllers
{
    /// <summary>
    /// 退还押金控制器
    /// </summary>
    public class RefundController : Controller
    {
        private readonly IRefundService _refundService;

        public RefundController(IRefundService refundService)
        {
            _refundService = refundService;
        }
        public IActionResult Index()
        {
            var dtoList = _refundService.FindList();
            List<RefundViewModel> modelList = new List<RefundViewModel>();

            dtoList.ForEach(r =>
            {
                modelList.Add(new RefundViewModel()
                {
                    AddTime = r.AddTime.ToString("yyyy-MM-dd HH:mm:ss"),
                    Status = r.Status,
                    Id = r.Id,
                    UserId = r.UserId,
                    Nickname = r.Nickname,
                    Account = r.Account,
                    Deposit = r.Deposit,
                    Money = r.Money,
                    AccountType = r.AccountType == "alipay" ? "支付宝" : r.AccountType,
                    Type = r.Type
                });
            });
            ViewBag.RefundList = modelList;
            return View();
        }

        /// <summary>
        /// 退款
        /// </summary>
        /// <param name="id">退款id</param>
        /// <returns></returns>
        [HttpPost]
        public IActionResult Refund(int id)
        {
            MessageBase result = new MessageBase();
            var dto = _refundService.Find(id);
            string s = AliPaySdk.FundTrans(dto.Account, dto.RealName, dto.Money.ToString(CultureInfo.InvariantCulture), dto.OutBizNo);
            if (s == "10000")
            {
                this._refundService.UpdateDeposit(id);
                result.Status = "true";
            }
            else
            {
                result.Status = Permanent.FAILED;
                result.Message = s;
            }

            return Json(result);
        }
    }
}

代码库/社区/PC端/Com.Cos/Com.Cos.Admin/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

代码库/社区/PC端/Com.Cos/Com.Cos.Admin/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

代码库/社区/PC端/Com.Cos/Com.Cos.Admin/Views/Home/Download.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1,maximum-scale=1,user-scalable=no">
    <title>download</title>
</head>
<body>
    <script src="https://cdn.staticfile.org/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdn.staticfile.org/mobile-detect/1.3.6/mobile-detect.min.js"></script>
    <script>
        //判断数组中是否包含某字符串
        Array.prototype.contains = function (needle) {
            for (i in this) {
                if (this[i].indexOf(needle) > 0)
                    return i;
            }
            return -1;
        }
        $(document).ready(function() {
            var device_type = navigator.userAgent;//获取userAgent信息
            //document.write(device_type);//打印到页面
            var md = new MobileDetect(device_type);//初始化mobile-detect
            var os = md.os();//获取系统
            var model = "";
            if (os == "iOS") {//ios系统的处理
                os = md.os() + md.version("iPhone");
                model = md.mobile();
                window.location.href = "https://itunes.apple.com/cn/app/id1145726508";
            } else if (os == "AndroidOS") {//Android系统的处理
                os = md.os() + md.version("Android");
                var sss = device_type.split(";");
                var i = sss.contains("Build/");
                if (i > -1) {
                    model = sss[i].substring(0, sss[i].indexOf("Build/"));
                }
                if (model.indexOf("MI")>-1) {  //小米
                    window.location.href = "http://app.mi.com/details?id=com.cos.huanhuan";
                } else if (model.indexOf("MX") > -1) { //魅族
                    window.location.href = "http://112.124.9.200/download/com.cos.huanhuan_9b2b59cdf5204f0e9ec4011442d4088b.apk";
                } else {
                    window.location.href = "http://112.124.9.200/download/com.cos.huanhuan_9b2b59cdf5204f0e9ec4011442d4088b.apk";
                }

            }

            //alert(os + "---" + model);//打印系统版本和手机型号
        });

    </script>
</body>
</html>

代码库/社区/PC端/Com.Cos/Com.Cos.Admin/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "H-ui.admin_v3.1";
}

<header class="navbar-wrapper">
    <div class="navbar navbar-fixed-top">
        <div class="container-fluid cl">
            <a class="logo navbar-logo f-l mr-10 hidden-xs" href="/aboutHui.shtml">H-ui.admin</a> <a class="logo navbar-logo-m f-l mr-10 visible-xs" href="/aboutHui.shtml">H-ui</a>
            <span class="logo navbar-slogan f-l mr-10 hidden-xs">v3.0</span>
            <a aria-hidden="false" class="nav-toggle Hui-iconfont visible-xs" href="javascript:;">&#xe667;</a>
            <nav class="nav navbar-nav">
                <ul class="cl">
                    <li class="dropDown dropDown_hover">
                        <a href="javascript:;" class="dropDown_A"><i class="Hui-iconfont">&#xe600;</i> 新增 <i class="Hui-iconfont">&#xe6d5;</i></a>
                        <ul class="dropDown-menu menu radius box-shadow">
                            <li><a href="javascript:;" onclick="article_add('添加资讯','article-add.html')"><i class="Hui-iconfont">&#xe616;</i> 资讯</a></li>
                            <li><a href="javascript:;" onclick="picture_add('添加资讯','picture-add.html')"><i class="Hui-iconfont">&#xe613;</i> 图片</a></li>
                            <li><a href="javascript:;" onclick="product_add('添加资讯','product-add.html')"><i class="Hui-iconfont">&#xe620;</i> 产品</a></li>
                            <li><a href="javascript:;" onclick="member_add('添加用户','member-add.html','','510')"><i class="Hui-iconfont">&#xe60d;</i> 用户</a></li>
                        </ul>
                    </li>
                </ul>
            </nav>
            <nav id="Hui-userbar" class="nav navbar-nav navbar-userbar hidden-xs">
                <ul class="cl">
                    <li>@User.Claims.SingleOrDefault(s => s.Type == "Nickname")?.Value</li>
                    <li class="dropDown dropDown_hover">
                        <a href="#" class="dropDown_A">@User.Claims.SingleOrDefault(s => s.Type == System.Security.Claims.ClaimTypes.Name)?.Value <i class="Hui-iconfont">&#xe6d5;</i></a>
                        <ul class="dropDown-menu menu radius box-shadow">
                            <li><a href="javascript:;" onclick="myselfinfo()">个人信息</a></li>
                            <li><a href="@Url.Action("Logout","Account")">切换账户</a></li>
                            <li><a href="@Url.Action("Logout","Account")">退出</a></li>
                        </ul>
                    </li>
                    <li id="Hui-msg"><a href="#" title="消息"><span class="badge badge-danger">1</span><i class="Hui-iconfont" style="font-size: 18px">&#xe68a;</i></a> </li>
                    <li id="Hui-skin" class="dropDown right dropDown_hover">
                        <a href="javascript:;" class="dropDown_A" title="换肤"><i class="Hui-iconfont" style="font-size: 18px">&#xe62a;</i></a>
                        <ul class="dropDown-menu menu radius box-shadow">
                            <li><a href="javascript:;" data-val="default" title="默认（黑色）">默认（黑色）</a></li>
                            <li><a href="javascript:;" data-val="blue" title="蓝色">蓝色</a></li>
                            <li><a href="javascript:;" data-val="green" title="绿色">绿色</a></li>
                            <li><a href="javascript:;" data-val="red" title="红色">红色</a></li>
                            <li><a href="javascript:;" data-val="yellow" title="黄色">黄色</a></li>
                            <li><a href="javascript:;" data-val="orange" title="橙色">橙色</a></li>
                        </ul>
                    </li>
                </ul>
            </nav>
        </div>
    </div>
</header>
<aside class="Hui-aside">
    <div class="menu_dropdown bk_2">
        <dl id="menu-product">
            <dt><i class="Hui-iconfont">&#xe620;</i> 兑换管理<i class="Hui-iconfont menu_dropdown-arrow">&#xe6d5;</i></dt>
            <dd>
                <ul>
                    <li><a data-href="@Url.Action("Index", "Exchange")" data-title="兑换管理" href="javascript:void(0)">兑换管理</a></li>
                    <li><a data-href="@Url.Action("Index", "ExchangePerson")" data-title="兑换人员管理" href="javascript:void(0)">兑换人员管理</a></li>
                </ul>
            </dd>
        </dl>
        <dl id="menu-member">
            <dt><i class="Hui-iconfont">&#xe60d;</i> 会员管理<i class="Hui-iconfont menu_dropdown-arrow">&#xe6d5;</i></dt>
            <dd>
                <ul>
                    <li><a data-href="@Url.Action("Index","Member")" data-title="会员列表" href="javascript:;">会员列表</a></li>
                    <li><a data-href="@Url.Action("Index","Refund")" data-title="用户退款管理" href="javascript:;">用户退款管理</a></li>
                    <li><a data-href="@Url.Action("Index","Member")" data-title="退款管理" href="javascript:;">退款处理</a></li>
                </ul>
            </dd>
        </dl>
        <dl id="menu-system">
            <dt><i class="Hui-iconfont">&#xe62e;</i> 系统管理<i class="Hui-iconfont menu_dropdown-arrow">&#xe6d5;</i></dt>
            <dd>
                <ul>
                    <li><a data-href="@Url.Action("Index","QuickNavigation")" data-title="数据字典" href="javascript:void(0)">数据字典</a></li>
                </ul>
            </dd>
        </dl>
    </div>
</aside>
<div class="dislpayArrow hidden-xs"><a class="pngfix" href="javascript:void(0);" onclick="displaynavbar(this)"></a></div>
<section class="Hui-article-box">
    <div id="Hui-tabNav" class="Hui-tabNav hidden-xs">
        <div class="Hui-tabNav-wp">
            <ul id="min_title_list" class="acrossTab cl">
                <li class="active">
                    <span title="我的桌面" data-href="Welcome.aspx">我的桌面</span>
                    <em></em>
                </li>
            </ul>
        </div>
        <div class="Hui-tabNav-more btn-group"><a id="js-tabNav-prev" class="btn radius btn-default size-S" href="javascript:;"><i class="Hui-iconfont">&#xe6d4;</i></a><a id="js-tabNav-next" class="btn radius btn-default size-S" href="javascript:;"><i class="Hui-iconfont">&#xe6d7;</i></a></div>
    </div>
    <div id="iframe_box" class="Hui-article">
        <div class="show_iframe">
            <div style="display: none" class="loading"></div>
            <iframe scrolling="yes" frameborder="0" src="@Url.Action("Welcome","Home")"></iframe>
        </div>
    </div>
</section>

<div class="contextMenu" id="Huiadminmenu">
    <ul>
        <li id="closethis">关闭当前 </li>
        <li id="closeall">关闭全部 </li>
    </ul>
</div>

@section Scripts{
    <environment include="Development">
        <script type="text/javascript" src="~/lib/jquery.contextmenu/jquery.contextmenu.r2.js"></script>
        <script type="text/javascript">
            $(function () {
                /*$("#min_title_list li").contextMenu('Huiadminmenu', {
                    bindings: {
                        'closethis': function(t) {
                            console.log(t);
                            if(t.find("i")){
                                t.find("i").trigger("click");
                            }
                        },
                        'closeall': function(t) {
                            alert('Trigger was '+t.id+'\nAction was Email');
                        },
                    }
                });*/
            });
            /*个人信息*/
            function myselfinfo() {
                layer.open({
                    type: 1,
                    area: ['300px', '200px'],
                    fix: false, //不固定
                    maxmin: true,
                    shade: 0.4,
                    title: '查看信息',
                    content: '<div>管理员信息</div>'
                });
            }

            /*资讯-添加*/
            function article_add(title, url) {
                var index = layer.open({
                    type: 2,
                    title: title,
                    content: url
                });
                layer.full(index);
            }
            /*图片-添加*/
            function picture_add(title, url) {
                var index = layer.open({
                    type: 2,
                    title: title,
                    content: url
                });
                layer.full(index);
            }
            /*产品-添加*/
            function product_add(title, url) {
                var index = layer.open({
                    type: 2,
                    title: title,
                    content: url
                });
                layer.full(index);
            }
            /*用户-添加*/
            function member_add(title, url, w, h) {
                layer_show(title, url, w, h);
            }


        </script>
    </environment>

}